(library
 (name pages)
 (wrapped true)
 (modules
  login
  contests
  problems
  scoreboard
  users
  dashboard
  submissions
  codeboard
  settings
  settings_user
  settings_yodac
  settings_stats
  settings_stats_graphs
  settings_helpers)
 (libraries
  components
  api
  i18n
  js_of_ocaml
  js_of_ocaml-tyxml
  tyxml
  js_of_ocaml-lwt
  lwt)
 (preprocess
  (pps js_of_ocaml-ppx)))
