(library
 (name components)
 (wrapped true)
 (modules
  contest_list
  login_form
  modal_view
  problem_dropdown
  problem_list
  scoreboard
  submissions_list
  user_list
  sidebar
  spinner_modal
  spinner_modal_update
  view_summary
  view_submissions
  view_problem
  view_problems
  view_contest_progress
  editor
  codebar
  tabbar
  testbar)
 (libraries
  api
  model
  helpers
  i18n
  js_of_ocaml
  js_of_ocaml-tyxml
  tyxml
  js_of_ocaml-lwt
  lwt)
 (preprocess
  (pps js_of_ocaml-ppx ppx_blob))
 (preprocessor_deps
  (file ../../static/yoda-cameling-loop.gif)))
